-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 2

NDefines.NDiplomacy.MAX_FREE_CITIES = 0
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 15

NDefines.NCountry.MIN_DEV_FOR_FREE_CITY = 5
NDefines.NCountry.MAX_PROVINCES_FOR_FREE_CITY = 3

NDefines.NCountry.SIBERIAN_TRIBE_MIGRATION_COOLDOWN_YEARS = 3

NDefines.NCountry.MONARCH_DEATH = 0
NDefines.NCountry.MONARCH_DEATH_MIN_CHANCE_MODIFIER = 0
NDefines.NCountry.HEIR_DEATH= 0

NDefines.NDiplomacy.INTEGRATE_VASSAL_MIN_YEARS = 20


NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.08
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.5
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_NONTRIBUTARY_DEV = -0.05

NDefines.NAI.FORT_MAINTENANCE_CHEAT = 1

NDefines.NAI.FORT_BUDGET_FRACTION = 0.5

NDefines.NCountry.BASE_HEIR_BIRTH = 50